### ISSUE TITLE
Mention OpenDNS SOA issues

### ISSUE THREAD

**Issue by ainar-g** [AdguardTeam/KnowledgeBaseDNS#16]
See AdguardTeam/AdGuardHome#4471.

Apparently, OpenDNS's servers remove `AUTHORITY` sections from some responses, including `NODATA` ones, which makes caching such responses impossible.  I'm not sure if there is a policy regarding documenting the quirks of particular DNS providers, but consider mentioning that fact.

**Comment by anastasiia-fedotova** [comment]
Hello! We've fixed this issue.
