### ISSUE TITLE
Update comss DNS server DNS-over-QUIC address

### ISSUE THREAD

**Issue by Refreezer** [AdguardTeam/KnowledgeBaseDNS#163]
https://adguard-dns.io/kb/general/dns-providers/#comssone-dns
`quic://dns.comss.one:784` address has been changed to `quic://dns.comss.one:853`
https://www.comss.ru/page.php?id=7315

**Comment by anastasiia-fedotova** [comment]
Thank you! We've updated the info.

**Comment by military1** [comment]
@anastasiia-fedotova, it is now based on Controld.  https://www.comss.ru/page.php?id=7315
DNS-over-HTTPS (DoH)
https://dns.controld.com/comss

DNS-over-TLS (DoT)
comss.dns.controld.com 

DNS-over-QUIC (DoQ)
comss.dns.controld.com
