### ISSUE TITLE
Many guides on https://adguard-dns.io/en/public-dns.html are outdated, wrong, or missing

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/KnowledgeBaseDNS#194]
Presuming this is the correct repo to report problems with the guides:

- [x] The "Nintendo" section should be renamed "Nintendo 3DS".
- [x] No Nintendo 3DS version (nor Wii U for that matter) support IPv6 at all, so that part of the guide should be removed.
- [x] Nintendo Switch doesn't support IPv6 either, so that part of the guide should be removed from the "Nintendo Switch" guide.
- [ ] Windows, primarily Windows 11 onwards, natively support DNS-over-HTTPS, so info about that should be added to the "Windows" section.
- [ ] I would be able to write a PS3 guide with relative ease on request.
* * I acknowledge that Epson printers and Yamaha surround receivers have so much different UIs between themselves, that writing any guides for those would not be possible.

**Comment by Chinaski1** [comment]
Hello there!

Thank you, we will definitely take your comments in acccount

**Comment by Chinaski1** [comment]
Internal ID: AGDNS-2020

**Comment by DandelionSprout** [comment]
Should it be of any relevance, there's also https://en.wikipedia.org/wiki/Comparison_of_IPv6_support_in_operating_systems to check for IPv6 support. (Disclaimer: I myself added info to that Wikipedia on Nintendo, PlayStation, Tizen, and Xbox One/Series.)

**Comment by Chinaski1** [comment]
We've changed the points you mentioned about Nintendo. 
Regarding PS3, I don't think there's any point in adding it as the console is obsolete
As for the instructions for setting up Windows, an advanced version is available in the instructions for setting up Private DNS.
