### ISSUE TITLE
Rendered web page partially broken

### ISSUE THREAD

**Issue by PeterDaveHello** [AdguardTeam/KnowledgeBaseDNS#50]
The description and title of ControlD in the DNS profiders page seems to be missing on the web page after being rendered

https://github.com/AdguardTeam/KnowledgeBaseDNS/blob/ff9a6b8b89a690825d1157a8fa2cf8cc8720a3be/docs/general/dns-providers.md?plain=1#L1047-L1086

![image](https://user-images.githubusercontent.com/3691490/177549308-66f42c23-d45e-4146-ba83-d25417859ebf.png)

**Comment by ameshkov** [comment]
Seems to be good in the master branch:
https://adguardteam.github.io/KnowledgeBaseDNS/general/dns-providers/#controld

Have not yet been published to the website though.
