### ISSUE TITLE
Local Yarn 1.22.19 update to 3.2.4 or latest yarn

### ISSUE THREAD

**Issue by kmunk1975** [AdguardTeam/KnowledgeBaseDNS#72]
"One moment though: please run the DNS KB locally and make sure it can be built properly (there're build instructions in the README). Openhack."

**Comment by ameshkov** [comment]
It should be okay to use the latest stable yarn version.

**Comment by kmunk1975** [comment]
Yes, but what command to use after yarn init --2
Because "start" are removed as command, i think also build are. New are run?
Im on windows 11.

**Comment by ameshkov** [comment]
I guess this can be closed now :)
