### ISSUE TITLE
Update Comss DNS addresses

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBaseDNS#81]
https://adguard-dns.io/kb/ru/general/dns-providers/#comssru-dns

It seems that SDNS stamps are invalid, they don't work when you click "Add to AdGuard".
We should update these addresses.

Just in case, Comss addresses are here:
https://www.comss.ru/page.php?id=7315

**Comment by vbagirov** [comment]
1) Comss.one DNS doesn't seem to have any plain or DNSCrypt addresses any more

2) AdGuard doesn't parse `tls://dns.east.comss.one` or corresponding sdns at all when you try to add such custom server manually. At the same time, according to the Comss website, their east server is up and running. Same for their East DoQ server `quic://dns.comss.one:784`. Not sure what to make of it, west servers can be added no problem, DoH, DoT, and DoQ alike.

**Comment by vbagirov** [comment]
After some time, Comss.one East DoT and DoQ addresses seem to work in every way possible.
