### ISSUE TITLE
Remove "beta testing" article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBaseDNS#88]
@jslawler commented on [Tue Jan 03 2023](https://github.com/AdguardTeam/AdGuardDNS/issues/492)

The AdGuard kb advertises the [Private AdGuard DNS beta test](https://adguard-dns.io/kb/miscellaneous/beta-testing/), even though this has ended (for now?).

Should it still be there?

**Comment by el-termikael** [comment]
https://github.com/AdguardTeam/KnowledgeBaseDNS/pull/89
