### ISSUE TITLE
[Question] Should a question mark be used for these strings?

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/KnowledgeBaseDNS#90]
The following are used without question marks. So do these need to have question marks?

<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/35523759/211317821-def9d6bb-f564-4197-ad0f-1de85f5f7228.png)
</details>

<details><summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/35523759/211318121-4deda4ae-5ab9-437a-846d-529d15e114f7.png)
</details>

<details><summary>Screenshot 3</summary>

![image](https://user-images.githubusercontent.com/35523759/211318344-c51949df-e5e6-47bd-bc8f-9b748cbe7d21.png)
</details>

**Comment by el-termikael** [comment]
Done! Please check the changed source strings on Crowdin: https://crowdin.com/translate/adguard-knowledge-bases/all/en-tr?filter=basic&value=0

**Comment by gork7777** [comment]
@el-termikael Thanks! Can you check these too? 

![image](https://user-images.githubusercontent.com/35523759/217596817-27c335aa-a660-4317-b1af-3491b531ac17.png)

**Comment by el-termikael** [comment]
these ones don't need question marks (the order of words is not like in questions)
